apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache0-deployment
  labels:
    app: apache0-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache0
  template:
    metadata:
      labels:
        app: apache0
    spec:
      containers:
      - name: apache
        image: k8s.gcr.io/nginx:1.7.9
        ports:
        - containerPort: 80
